### ISSUE TITLE
Would you consider publishing weights so that the model can be tested without traning?

### ISSUE THREAD

**Issue by PiotrCzapla** [darsh10/qra_code#1]
Hi,
Thank you for publishing the code. Would you consider publishing weights as well so that it is possible to check how the model works without need to run training?

Regards,
Piotr

**Comment by PiotrCzapla** [comment]
Hi, Anyone there?

**Comment by darsh10** [comment]
Hi Piotr,
Apologies for the delay. Which domain pair in particular would you like to use ? Also, solely evaluating the model will involve using the same code base. Is there any issue in particular that you would like us to consider in training the code ?

**Comment by PiotrCzapla** [comment]
I was trying to evaluate your model on my dataset. Weights can be used to test the repository that it runs at least the inference fairly quickly, which removes a large portion of potential issues (pytorch compatibility etC). This would help me to  work towards reproducing your results on a custom dataset.
