### ISSUE TITLE
Quora dataset splits mentioned in paper and open-sourced one differs hugely

### ISSUE THREAD

**Issue by thakur-nandan** [darsh10/qra_code#2]
Hi Darsh, 

I wanted to reciprocate the work mentioned in your paper titled "https://www.aclweb.org/anthology/D18-1131.pdf".

Datasets apart from Quora are accurate, so no issues.

For Quora in Table 1 of your paper, you mention you have 9100 positive pairs for training, so accordingly you would have trained with 910,000 negatives, keeping 100 negative question pairs per positive pair. 

But in the data which you open-source, here are the sizes of Quora dataset - 

Split | Pos. | Neg.
--- | --- | ---
Full | 149306 | 255042 |
Train | 139306 | 245042 | 
Dev | 5000 | 5000 | 
Test | 5000 | 5000 | 

Since, 255,042 < 910,000 negative pairs, how to get the rest of the negative samples? Or is this ratio not balanced in the ratio of 1 pos: 100 negs? Could you also provide the final splits for Quora?

Kind Regards,
Nandan Thakur

**Comment by darsh10** [comment]
Hey,

That’s a great question. I took the first 9100 for training and all the
available negative for testing.

**Comment by thakur-nandan** [comment]
Thanks for the prompt response @darsh10,

you mean rest available negative for training right?

Also, did you chose the 9100 randomly sampling or literally the first 9100 from the positives file?

Kind Regards,
Nandan Thakur

**Comment by darsh10** [comment]
First 9100

**Comment by thakur-nandan** [comment]
Thank you.
