### ISSUE TITLE
Using Content and Title for every dataset apart from Quora?

### ISSUE THREAD

**Issue by thakur-nandan** [darsh10/qra_code#3]
Hi @darsh10,
Quora dataset, as can be found only contains question titles, whereas all the other datasets apart from Quora, contain both a question content and title. As far as I have understood, the parameters: (use_content and eval_use_content) enables the utilization of the question content. 

Do you train and evaluate the adversarial model all for datasets (apart from Quora) with both question content and title?
Only for datasets (with Quora), you train and evaluate the adversarial model with just question title?
Also if I'm not wrong from the code, you concatenate both the content vector and title vector and find the cosine similarity between these?

Just wanted to confirm these doubts.
Thank you in advance.

Kind Regards,
Nandan Thakur

**Comment by darsh10** [comment]
Hi Nandan,

The Quora dataset by nature doesn't have a body. You can repeat the title
as the body.

Yes, only for Quora it is without the body.

I believe it is an average of the title and body.
